import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-100 px-4 sm:px-8 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center">
          <span className="font-semibold text-slate-800 tracking-tight">my</span>
          <img src="/favicon.ico" alt="myCVtailor.co.za" className="w-5 h-5" />
          <span className="font-semibold text-slate-800 tracking-tight">tailor.co.za</span>
        </Link>
        <Link href="/" className="text-xs text-slate-400 hover:text-slate-700 transition-colors">← Back</Link>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-4xl font-semibold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: March 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-sm text-slate-600 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using myCVtailor.co.za ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">2. Description of Service</h2>
            <p>myCVtailor.co.za is an AI-powered CV tailoring platform that rewrites your CV to match job descriptions and pass ATS filters. The Service is provided on a credit-based system where users purchase tailor credits to generate optimised CVs and cover letters.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">3. User Accounts</h2>
            <p>You must sign in with a valid Google account to use the Service. You are responsible for maintaining the security of your account and all activities that occur under it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">4. Credits and Payments</h2>
            <p>Credits are purchased on a one-time basis and never expire. Credits are non-transferable and may not be resold. All payments are processed securely through our payment provider. Prices are listed in USD.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">5. Refund Policy</h2>
            <p>We offer a 7-day money-back guarantee on all credit purchases. If you are unsatisfied with the Service, contact us within 7 days of purchase at nyamfusima@gmail.com for a full refund. Refunds are not available for credits that have already been used.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">6. Data and Privacy</h2>
            <p>Your CV and job description data is processed in real time and is never stored on our servers. We do not sell or share your personal data with third parties. Please refer to our Privacy Policy for full details.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">7. Intellectual Property</h2>
            <p>You retain full ownership of all CVs and documents you upload or generate using the Service. myCVtailor.co.za does not claim any rights over your content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">8. Acceptable Use</h2>
            <p>You agree not to misuse the Service, attempt to reverse engineer it, or use it for any unlawful purpose. We reserve the right to suspend accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">9. Limitation of Liability</h2>
            <p>myCVtailor.co.za is provided "as is" without warranties of any kind. We are not responsible for any job application outcomes or decisions made by employers based on CVs generated by the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">10. Changes to Terms</h2>
            <p>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">11. Contact</h2>
            <p>For any questions about these terms, contact us at <a href="mailto:nyamfusima@gmail.com" className="underline" style={{ color: "#0d1f3c" }}>nyamfusima@gmail.com</a></p>
          </section>

        </div>
      </main>

      <footer className="border-t border-slate-100 px-4 sm:px-8 py-6 flex flex-col sm:flex-row items-center justify-between gap-2 mt-8">
        <div className="flex items-center">
          <span className="text-sm text-slate-400">my</span>
          <img src="/favicon.ico" alt="myCVtailor.co.za" className="w-4 h-4" />
          <span className="text-sm text-slate-400">tailor.co.za</span>
        </div>
        <div className="flex items-center gap-4 text-xs text-slate-400">
          <Link href="/terms" className="hover:text-slate-700">Terms</Link>
          <Link href="/privacy" className="hover:text-slate-700">Privacy</Link>
          <Link href="/refunds" className="hover:text-slate-700">Refunds</Link>
        </div>
      </footer>
    </div>
  );
}
